# Usage: KITCHEN_YAML=.kitchen.vmware.yml bundle exec kitchen list
---
driver:
  name: vagrant
  provider: vmware_fusion
  customize:
    memory: 2048

provisioner:
  name: chef_solo
  chef_license: accept
  require_chef_omnibus: 14.7.17

verifier:
  name: inspec

platforms:
  - name: macosx-10.10
    driver:
      box: macosx-10.10
    driver_config:
      network:
      - ["forwarded_port", {guest: 8081, host: 8081}]

suites:
- name: nexus_test
