---
driver:
  name: localhost

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.6.4

verifier:
  name: inspec

platforms:
  - name: macosx-10

suites:
- name: default
  run_list:
    - nexus3_test::default
    - nexus3_resources_test::default
  attributes:
