# Usage: KITCHEN_YAML=.kitchen.docker.yml bundle exec kitchen list
---
driver:
  name: dokken
  chef_version: 13.6.4
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: centos-7
  driver:
    image: centos:7
    intermediate_instructions:
      - RUN yum clean all
      - RUN yum -y install net-tools lsof
    pid_one_command: /usr/lib/systemd/systemd

- name: fedora-29
  driver:
    image: fedora:29
    intermediate_instructions:
    - RUN yum clean all
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install tar yum

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools curl -y

suites:
- name: default
  run_list:
    - nexus3_test::default
    - nexus3_resources_test::default
    - nexus3_test::integration
  attributes:
    nexus3_test:
      connection_retries: 10
    nexus3:
      api:
        sensitive: false
