---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_solo
  require_chef_omnibus: 13.6.4

verifier:
  name: inspec

platforms:
  - name: centos-7.1
    driver:
      network:
      - ["forwarded_port", {guest: 8081, host: 8081}]

  - name: ubuntu-14.04
    driver:
      network:
      - ["forwarded_port", {guest: 8081, host: 8082}]

  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2
      network:
      - ["forwarded_port", {guest: 8081, host: 8083}]

suites:
  - name: default
    run_list:
      - nexus3_test::default
      - nexus3_resources_test::default
    attributes:
       nexus3_test:
         connections_retries: 10
       nexus3:
         api:
           sensitive: false
           live_stream: false
           fail: false
