AllCops:
  Exclude:
    - '.kitchen/**/*'
    - 'vendor/**/*'

LineLength:
  Max: 120

MethodLength:
  Max: 60

AbcSize:
  Max: 60

BlockLength:
  Max: 130

Style/FormatString:
  Exclude: ['spec/**/*', 'test/**/*']
