AllCops:
  Exclude:
    - '.kitchen/**/*'
    - 'vendor/**/*'
    - 'test/fixtures/cookbooks/nexus3_resources_test/attributes/*'

Layout/LineLength:
  Max: 150

Layout/MethodLength:
  Max: 60

Layout/AbcSize:
  Max: 60

Layout/BlockLength:
  Max: 130

Naming/FileName:
  Exclude:
  - Policyfile.rb # this is chef names

Style/FormatString:
  Exclude: ['spec/**/*', 'test/**/*']

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 8
